routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('markets', 'MarketController');

Route::get('getProducts', 'HomeController@getProducts');
Route::get('/productShow/{product}', 'HomeController@ProductShow')->name('productShow');
Route::get('/marketShow/{market}', 'HomeController@MarketShow')->name('marketShow');
Route::get('markets/{market}/products', 'MarketController@MarketProducts')->name('markets.products');
Route::post('markets/addProduct', 'MarketController@addProduct');
Route::post('markets/removeProduct', 'MarketController@removeProduct');
Route::get('market-all', 'HomeController@markets')->name('markets');
Route::get('category-all', 'HomeController@categories')->name('categories');
Route::get('category-all/{category}/show', 'HomeController@categoryShow')->name('category-show');

Route::get('/search', 'SearchController@search')->name('search');
Route::post('/getNearestMarkets/', 'SearchController@nearest')->name('nearest');

Route::group(['middleware' => 'basket_is_not_empty'], function (){
    Route::get('basket', 'BasketController@basket')->name('basket');
    Route::get('basket/place', 'BasketController@basketPlace')->name('basketPlace');
    Route::post('basket/remove/{product}', 'BasketController@basketRemove')->name('basketRemove');
    Route::post('basket/place', 'BasketController@basketConfirm')->name('basketConfirm');
});
Route::post('/basket/add/{product}', 'BasketController@basketAdd')->name('basketAdd');
Route::get('/orders', 'OrderController@index')->name('orders.index');
Route::get('/order/{order}', 'OrderController@show')->name('orders.show');
Route::get('/incomingOrders', 'OrderController@incomingOrders')->name('incomingOrders');
Route::get('incomingOrderShow/{order}', 'OrderController@incomingOrderShow')->name('incomingOrderShow');

Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');


Route::get('/getBasket', 'BasketController@getBasketForAjax');
//Route::get('/getCountOfProducts', 'BasketController@getCountOfProducts');

Route::get('/getCategories', 'CategoriesController@getCategories');
Route::get('/getProducts', 'HomeController@getProducts');
Route::post('/uploadImageForProduct', 'ProductsController@image');
Route::get('/getIncomingOrders', 'OrderController@getIncomingOrders');
Route::get('/', function (){
    return view('vue');
})->name('vue-home');


Route::get('/statistic', 'StatisticController@index')->name('statistic');
Route::get('/getStatistic', 'StatisticController@getStatistic');
Route::get('/getTopTrendingProducts', 'StatisticController@getTopTrendingProducts');
Route::get('/getOrdersStatistic', 'StatisticController@getOrdersStatistic');
Route::get('/getTotalOrdersSum', 'StatisticController@getTotalOrdersSum');
Route::get('/getCategoriesStatistic', 'StatisticController@getCategoriesStatistic');


Route::get('login/google', 'Auth\LoginController@redirectToProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');

app/Market.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Market extends Model
{
    protected $fillable = ['name', 'description', 'location', 'lat', 'lng', 'user_id'];

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }



}

app/Http/Controllers/MarketController.php
<?php

namespace App\Http\Controllers;

use App\Market;
use App\Repositories\ProductRepository;
use App\Services\MarketService;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MarketController extends Controller
{
private $marketService;
    /**
     * @var \Illuminate\Contracts\Foundation\Application|mixed
     */
    private $productRepository;

    public function __construct(MarketService $marketService)
    {
        $this->middleware('auth');
        $this->marketService = $marketService;
        $this->productRepository = app(ProductRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $markets = $this->marketService->getAllMarkets(Auth::user());
        return view('markets.index', compact('markets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('markets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = collect($request->all());
        $user_id = Auth::user();
        $result = $this->marketService->createMarket($data, $user_id);
        if ($result)
        {
            return redirect()->route('markets.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Market  $market
     * @return \Illuminate\Http\Response
     */
    public function show(Market $market)
    {
        return view('markets.show', compact('market'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Market  $market
     * @return \Illuminate\Http\Response
     */
    public function edit(Market $market)
    {
        if ($this->marketService->checkOwner($market, Auth::user()))
        {
            return view('markets.edit', compact('market'));
        }else{
            return  redirect()->back();
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Market  $market
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Market $market)
    {
        if ($this->marketService->checkOwner($market, Auth::user())) {
            $data = collect($request->all());
            $user = Auth::user();
            $result = $this->marketService->updateMarket($data, $market, $user);
            if ($result) {
                return redirect()->route('markets.index');
            } else {
                return redirect()->back();
            }
        }else{
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Market  $market
     * @return \Illuminate\Http\Response
     */
    public function destroy(Market $market)
    {
        if ($this->marketService->checkOwner($market, Auth::user())) {
            if ($market->delete()) {
                return redirect()->route('markets.index');
            } else {
                return false;
            }
        }else{
            return redirect()->back();
        }
    }

    public function MarketProducts(Market $market)
    {
        $products = $this->productRepository->getAllProducts(Auth::user());
        return view('markets.products', compact('products', 'market'));
    }

    public function addProduct(Request $request)
    {
        $product_id = $request->get('product_id');
        $market_id = $request->get('market_id');
        $result = $this->marketService->attachProduct($product_id , $market_id);

        if ($result)
        {
            return response()->json(['status' => 'success']);
        }else{
            return response()->json(['status' => 'fail']);
        }
    }

    public function removeProduct(Request $request)
    {
        $product_id = $request->get('product_id');
        $market_id = $request->get('market_id');
        $result = $this->marketService->detachProduct($product_id, $market_id);
        if ($result)
        {
            return response()->json(['status' => 'success']);
        }else{
            return response()->json(['status' => 'fail']);
        }
    }
}

resources/views/markets/create.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'create market')
@section('content')
    <div class="container">
        <form action="{{route('markets.store')}}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" name="name" id="name" class="form-control" >
            </div>
            @error('name')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="content">description</label>
                <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
            </div>
            @error('description')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror

            <div class="form-group">
                <label for="address_address">Address</label>
                <input type="text" id="address-input" name="address_address" class="form-control map-input">
                <input type="hidden" name="address_latitude" id="address-latitude" value="0" />
                <input type="hidden" name="address_longitude" id="address-longitude" value="0" />
            </div>
            <div id="address-map-container" style="width:100%;height:400px; ">
                <div style="width: 100%; height: 100%" id="address-map"></div>
            </div>
            <button type="submit" class="btn btn-outline-info btn-block">create</button>
            @csrf
        </form>
    </div>
@endsection

resources/views/markets/edit.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'edit market'.$market->name)
@section('content')
    <div class="container">
        <form action="{{route('markets.update', [$market])}}" method="post" enctype="multipart/form-data">
            @method('PATCH')
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" name="name" id="name" class="form-control" value="{{old('name', isset($market)? $market->name :null)}}">
            </div>
            @error('name')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="content">description</label>
                <textarea name="description" id="description" cols="30" rows="10" class="form-control">{{old('description', isset($market)? $market->description :null)}}</textarea>
            </div>
            @error('description')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror

            <div class="form-group">
                <label for="address_address">Address</label>
                <input type="text" id="address-input" name="address_address" class="form-control map-input" value="{{old('address_address', isset($market)? $market->location :null)}}">
                <input type="hidden" name="address_latitude" id="address-latitude" value="{{old('address_latitude', isset($market)? $market->lat :null)}}" />
                <input type="hidden" name="address_longitude" id="address-longitude" value="{{old('address_longitude', isset($market)? $market->lng :null)}}" />
            </div>
            <div id="address-map-container" style="width:100%;height:400px; ">
                <div style="width: 100%; height: 100%" id="address-map"></div>
            </div>
            <button type="submit" class="btn btn-outline-info btn-block">update</button>
            @csrf
        </form>
    </div>
@endsection

resources/views/markets/index.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'admin markets')
@section('content')
    <div class="container">
        <h2>markets page</h2>
        <table class="table table-light">
            <thead>
            <tr>
                <th>id</th>
                <th>name</th>
                <th>description</th>
                <th>location</th>
                <th>action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($markets as $market)
                <tr >
                    <div class="row d-flex flex-wrap">
                    <div class="col">
                    <th scope="row">{{$market->id}}</th>
                    <td>
                        <a href="{{route('marketShow', [$market])}}">    {{$market->name}}</a>
                    </td>
                    <td>
                        {{$market->description}}
                    </td>
                    <td>{{$market->location}}</td>
                    </div>
                    <div class="">
                    <th class="">
                        <form action="{{route('markets.destroy', $market)}}" method="POST" >
                            <div class="row justify-content-center flex-nowrap ">
                          <div > <a class="mx-1 text-center btn btn-outline-success" href="{{route('markets.show', [$market])}}" >show</a></div>
                         <div >  <a class="mx-1 text-center btn btn-warning" href="{{route('markets.edit', [$market])}}">edit</a></div>
                            @csrf
                            @method('DELETE')
                        <div >    <button type="submit" class="mx-1 text-center btn btn-danger" value="delete">delete</button></div>
                     <div > <a href="{{route('markets.products', [$market])}}" class="mx-1  text-center btn btn-group btn-outline-info">products</a>
                            </div>    </div>
                        </form></th></div></div>
                </tr>
            @endforeach
            </tbody>
        </table>
        <a class="btn btn-group btn-success" href="{{route('markets.create')}}">create</a>
        <div class="w-100 d-flex justify-content-center">

        </div>
    </div>

@endsection

resources/views/markets/products.blade.php
<?php
?>


@extends('layouts.app')
@section('title', 'admin market products')
@section('content')
    <div class="container">
        <h2>{{$market->name}} products</h2>
        <span id="marketID" data-id="{{$market->id}}" hidden></span>
        <table class="table table-light">
            <thead>
            <tr>
                <th>id</th>
                <th>name</th>
                <th>price</th>
                <th>categories</th>
            </tr>
            </thead>
            <tbody>
            @foreach( $products as $product)
                <tr>
                    <th scope="row">{{$product->id}}</th>
                    <td>
                        {{$product->name}}
                    </td>
                    <td>
                        {{$product->price}}$
                    </td>
                     <td>
                         @foreach($product->categories as $category)
                             {{$category->name}}
                         @endforeach
                     </td>
                    <td>
                        <div class="custom-control custom-switch">
                            <input type="checkbox" class="custom-control-input" id="product-{{$product->id}}" data-product="{{$product->id}}" name="product-{{$product->id}}" @if($market->products->contains($product)) checked @endif>
                            <label class="custom-control-label" for="product-{{$product->id}}">add product to market</label>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/markets/show.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'market: '.$market->name)
@section('content')
    <div class="container">
        <h2> {{$market->name}}</h2>
        <div >
            <p>{{$market->description}}</p>
        </div>
        <div class="location"><h3>location: </h3>{{$market->location}}</div>
        <div class="form-group">
            <label for="address_address">Address</label>
            <input type="text" id="address-input" name="address_address" class="form-control map-input" hidden>
            <input type="hidden" name="address_latitude" id="address-latitude" value="{{$market->lat}}" />
            <input type="hidden" name="address_longitude" id="address-longitude" value="{{$market->lng}}" />
        </div>
        <div id="address-map-container" style="width:100%;height:300px; ">
            <div style="width: 100%; height: 100%" id="address-map"></div>
        </div>
    </div>
@endsection