routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('markets', 'MarketController');

Route::get('getProducts', 'HomeController@getProducts');
Route::get('/productShow/{product}', 'HomeController@ProductShow')->name('productShow');
Route::get('/marketShow/{market}', 'HomeController@MarketShow')->name('marketShow');
Route::get('markets/{market}/products', 'MarketController@MarketProducts')->name('markets.products');
Route::post('markets/addProduct', 'MarketController@addProduct');
Route::post('markets/removeProduct', 'MarketController@removeProduct');
Route::get('market-all', 'HomeController@markets')->name('markets');
Route::get('category-all', 'HomeController@categories')->name('categories');
Route::get('category-all/{category}/show', 'HomeController@categoryShow')->name('category-show');

Route::get('/search', 'SearchController@search')->name('search');
Route::post('/getNearestMarkets/', 'SearchController@nearest')->name('nearest');

Route::group(['middleware' => 'basket_is_not_empty'], function (){
    Route::get('basket', 'BasketController@basket')->name('basket');
    Route::get('basket/place', 'BasketController@basketPlace')->name('basketPlace');
    Route::post('basket/remove/{product}', 'BasketController@basketRemove')->name('basketRemove');
    Route::post('basket/place', 'BasketController@basketConfirm')->name('basketConfirm');
});
Route::post('/basket/add/{product}', 'BasketController@basketAdd')->name('basketAdd');
Route::get('/orders', 'OrderController@index')->name('orders.index');
Route::get('/order/{order}', 'OrderController@show')->name('orders.show');
Route::get('/incomingOrders', 'OrderController@incomingOrders')->name('incomingOrders');
Route::get('incomingOrderShow/{order}', 'OrderController@incomingOrderShow')->name('incomingOrderShow');

Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');


Route::get('/getBasket', 'BasketController@getBasketForAjax');
//Route::get('/getCountOfProducts', 'BasketController@getCountOfProducts');

Route::get('/getCategories', 'CategoriesController@getCategories');
Route::get('/getProducts', 'HomeController@getProducts');
Route::post('/uploadImageForProduct', 'ProductsController@image');
Route::get('/getIncomingOrders', 'OrderController@getIncomingOrders');
Route::get('/', function (){
    return view('vue');
})->name('vue-home');


Route::get('/statistic', 'StatisticController@index')->name('statistic');
Route::get('/getStatistic', 'StatisticController@getStatistic');
Route::get('/getTopTrendingProducts', 'StatisticController@getTopTrendingProducts');
Route::get('/getOrdersStatistic', 'StatisticController@getOrdersStatistic');
Route::get('/getTotalOrdersSum', 'StatisticController@getTotalOrdersSum');
Route::get('/getCategoriesStatistic', 'StatisticController@getCategoriesStatistic');


Route::get('login/google', 'Auth\LoginController@redirectToProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'description'];
     public function products()
     {
         return $this->belongsToMany(Product::class);
     }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CategoryRequest;
use App\Repositories\CategoriesRepository;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{

    private $categoriesRepository;
    public function __construct(CategoriesRepository $categoriesRepository)
    {
        $this->categoriesRepository = $categoriesRepository;
        $this->middleware('IsAdmin')->except('index', 'getCategories');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoriesRepository->getAllCategories();
        return view('categories.index', compact('categories'));
    }

    public function getCategories()
    {
        $categories = $this->categoriesRepository->getAllCategories();
        return response()->json($categories);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $data = $request->only(['name', 'description']);
        $data['image'] = 'images/'.$request->get('imageName');
        $result = $this->categoriesRepository->createCategory($data);
        if ($result)
        {
            return redirect()->route('categories.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
      return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $data = $request->only(['name', 'description']);
        $data['image'] = 'images/'.$request->get('imageName');
        $result = $this->categoriesRepository->editCategory($data, $category);
        if ($result)
        {
            return redirect()->route('categories.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if ($category->delete())
        {
            return redirect()->route('categories.index');
        }

    }
}

resources/views/categories/create.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'create category')
@section('content')
    <div class="container">
        <form action="{{route('categories.store')}}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" name="name" id="name" class="form-control" >
            </div>
            @error('name')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="content">description</label>
                <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
            </div>
            @error('description')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror

            <button type="submit" class="btn btn-outline-info btn-block">create</button>
            @csrf
        </form>
    </div>
@endsection

resources/views/categories/edit.blade.php
<?php
?>

@extends('layouts.app')
@section('title', 'edit category: '.$category->name)
@section('content')
    <div class="container">
        <form action="{{route('categories.update', [$category])}}" method="POST">
            @method('PATCH')
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" name="name" class="form-control" required value="{{old('name', isset($category)? $category->name : null)}}">
            </div>
            @error('name')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="description">description</label>
                <textarea type="text" name="description" class="form-control" rows="6">{{old('description', isset($category)? $category->description : null)}}
                </textarea>
            </div>
            @error('description')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <button type="submit" class="btn btn-outline-info btn-block">update</button>
            @csrf
        </form>
    </div>
@endsection

resources/views/categories/index.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'admin category')
@section('content')
    <div class="container">
        <div id="adminCats">
        <admin-categories-component ></admin-categories-component>

        </div>
         <div class="w-100 d-flex justify-content-center">

        </div>
    </div>

@endsection

resources/views/categories/show.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'category: '.$category->name)
@section('content')
<div class="container">
        <h2>Tag: {{$category->name}}</h2>
        <div >
            <p>{{$category->description}}</p>
        </div>
    </div>
@endsection