routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('markets', 'MarketController');

Route::get('getProducts', 'HomeController@getProducts');
Route::get('/productShow/{product}', 'HomeController@ProductShow')->name('productShow');
Route::get('/marketShow/{market}', 'HomeController@MarketShow')->name('marketShow');
Route::get('markets/{market}/products', 'MarketController@MarketProducts')->name('markets.products');
Route::post('markets/addProduct', 'MarketController@addProduct');
Route::post('markets/removeProduct', 'MarketController@removeProduct');
Route::get('market-all', 'HomeController@markets')->name('markets');
Route::get('category-all', 'HomeController@categories')->name('categories');
Route::get('category-all/{category}/show', 'HomeController@categoryShow')->name('category-show');

Route::get('/search', 'SearchController@search')->name('search');
Route::post('/getNearestMarkets/', 'SearchController@nearest')->name('nearest');

Route::group(['middleware' => 'basket_is_not_empty'], function (){
    Route::get('basket', 'BasketController@basket')->name('basket');
    Route::get('basket/place', 'BasketController@basketPlace')->name('basketPlace');
    Route::post('basket/remove/{product}', 'BasketController@basketRemove')->name('basketRemove');
    Route::post('basket/place', 'BasketController@basketConfirm')->name('basketConfirm');
});
Route::post('/basket/add/{product}', 'BasketController@basketAdd')->name('basketAdd');
Route::get('/orders', 'OrderController@index')->name('orders.index');
Route::get('/order/{order}', 'OrderController@show')->name('orders.show');
Route::get('/incomingOrders', 'OrderController@incomingOrders')->name('incomingOrders');
Route::get('incomingOrderShow/{order}', 'OrderController@incomingOrderShow')->name('incomingOrderShow');

Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');


Route::get('/getBasket', 'BasketController@getBasketForAjax');
//Route::get('/getCountOfProducts', 'BasketController@getCountOfProducts');

Route::get('/getCategories', 'CategoriesController@getCategories');
Route::get('/getProducts', 'HomeController@getProducts');
Route::post('/uploadImageForProduct', 'ProductsController@image');
Route::get('/getIncomingOrders', 'OrderController@getIncomingOrders');
Route::get('/', function (){
    return view('vue');
})->name('vue-home');


Route::get('/statistic', 'StatisticController@index')->name('statistic');
Route::get('/getStatistic', 'StatisticController@getStatistic');
Route::get('/getTopTrendingProducts', 'StatisticController@getTopTrendingProducts');
Route::get('/getOrdersStatistic', 'StatisticController@getOrdersStatistic');
Route::get('/getTotalOrdersSum', 'StatisticController@getTotalOrdersSum');
Route::get('/getCategoriesStatistic', 'StatisticController@getCategoriesStatistic');


Route::get('login/google', 'Auth\LoginController@redirectToProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{

    use softDeletes;
    protected $fillable = ['name', 'description', 'price', 'image', 'count','user_id'];

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function markets()
    {
        return $this->belongsToMany(Market::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function orders()
    {
        return $this->belongsToMany(Order::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function isAvaible(){

        return $this->count > 0 && !$this->trashed();
    }
}

app/Http/Controllers/Api/ProductsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Api\Controller;
use App\Product;
use App\Repositories\ProductRepository;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Tymon\JWTAuth\Exceptions\UserNotDefinedException;
use App\Category;

class ProductsController extends Controller
{
    /**
     * @var ProductRepository|\Illuminate\Contracts\Foundation\Application|mixed
     */
    private $productRepository;

    public function __construct()
    {
        $this->productRepository = app(ProductRepository::class);
    }

    public function getN(Request $request)
    {
        return response()->json($request->all());
    }
    public function getProd(Request $request)
    {

        $products = $this->productRepository->getAllProducts(auth()->user(), $request->category ? $request->category : null);

        return response()->json($products);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Product;
use App\Repositories\CategoriesRepository;
use App\Services\ProductsService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProductsController extends Controller
{

    /**
     * @var ProductsService
     */
    private $productsService;
    /**
     * @var CategoriesRepository
     */
    private $categoriesRepository;

    public function __construct(ProductsService $productsService, CategoriesRepository $categoriesRepository)
    {
        $this->productsService = $productsService;
        $this->middleware('auth');
        $this->categoriesRepository = $categoriesRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->productsService->getAllProducts(Auth::user());
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories =  $this->categoriesRepository->getAllCategories();
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $data = collect($request->all());
        $data['user_id'] = Auth::id();
         $this->productsService->createProduct($data);
            return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $recommendProducts = $this->productsService->getRecommendProducts($product) ;
        return view('products.show', compact('product', 'recommendProducts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {

        $checkOwner = $this->productsService->CheckOwner($product, Auth::user());
        if ($checkOwner)
        {
            $categories = $this->categoriesRepository->getAllCategories();
            return view('products.edit', compact('categories', 'product'));
        }else{
            return redirect()->back();
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Product $product)
    {
        $data = collect($request->all());
        $this->productsService->updateProduct($data, $product);
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $checkOwner = $this->productsService->CheckOwner($product, Auth::user());
        if ($checkOwner) {
            if ($product->delete()) {
                return redirect()->back();
            } else {
                session()->flash('warning', 'can`t delete this product ');

                return false;
            }
        }else{
            return redirect()->back();
        }
    }
    public function getProducts()
    {
        $products = $this->productsService->getAllProducts(Auth::user());
        return response()->json($products);
    }
    public function image(Request $request){
        $request->image->move(storage_path().'/app/public/images', $request->imageName);
        return response()->json(['success'=>'You have successfully upload image.']);
    }
}

resources/views/products/create.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'create product')
@section('content')
    <div class="container">
        <form action="{{route('products.store')}}" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" name="name" id="name" class="form-control" >
            </div>
            @error('name')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="description">description</label>
                <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
            </div>
            @error('description')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror

            <div class="form-group">
                <select name="categories[]" id="categories" multiple="multiple" class="form-control" >
                    @foreach($categories as $category)
                        <option value="{{$category->name}}" >{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
            @error('categories')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input " id="customSwitch1" >
                    <label class="custom-control-label" for="customSwitch1">has image</label>
                </div>
                <div class="form-group">
                    <input id="image" type="file" class="form-controll-file" name="image" >
                </div>
                @error('image')
                <p class="alert alert-warning">{{$message}}</p>
                @enderror
                <div class="form-group">
                    <label for="price">price</label>
                    <input type="number" name="price" id="price" class="form-control" >
                </div>
                @error('price')
                <p class="alert alert-warning">{{$message}}</p>
                @enderror
                <div class="form-group">
                    <label for="count">count</label>
                    <input type="number" name="count" id="count" class="form-control" >
                </div>
                @error('count')
                <p class="alert alert-warning">{{$message}}</p>
                @enderror
            <button type="submit" class="btn btn-outline-info btn-block">create</button>
            @csrf
        </form>
    </div>

@endsection

resources/views/products/edit.blade.php
<?php
?>
@extends('layouts.app')
@section('title', 'edit product: '.$product->name)
@section('content')
    <div class="container">
        <form action="{{route('products.update', [$product])}}" method="POST" enctype="multipart/form-data">
            @method('PATCH')
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" name="name" class="form-control" required value="{{old('name', isset($product)? $product->name : null)}}">
            </div>
            @error('name')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="description">description</label>
                <textarea type="text" name="description" class="form-control"  rows="6" cols="10">{{old('description', isset($product)? $product->description : null)}}
                </textarea>
            </div>
            @error('description')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <select name="categories[]" id="categories" multiple="multiple" class="form-control" >
                    @foreach($categories as $category)
                        <option value="{{$category->name}}" @if($product->categories->contains($category)) selected @endif>{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
            @error('categories')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror

            <div class="form-group">
                <label for="image">image</label><br>
                <input id="image" type="file" class="form-controll-file" name="image" >
            </div>
            @error('image')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="price">price</label>
                <input type="number" name="price" id="price" class="form-control" value="{{old('price', isset($product)? $product->price : null)}}">
            </div>
            @error('price')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <div class="form-group">
                <label for="count">count</label>
                <input type="number" name="count" id="count" class="form-control" value="{{old('count', isset($product)? $product->count : null)}}">
            </div>
            @error('count')
            <p class="alert alert-warning">{{$message}}</p>
            @enderror
            <button type="submit" class="btn btn-outline-info btn-block">update</button>
            @csrf
        </form>
    </div>
@endsection

resources/views/products/index.blade.php
<?php
?>

@extends('layouts.app')
@section('title', 'admin products')
@section('content')
    <div class="container">

        <div id="adminProducts">
            <admin-products-component />
        </div>



@endsection

resources/views/products/show.blade.php
<?php
?>
@extends('layouts.app')
@section('title', $product->name)
@section('content')
    <h2 class="text-center">{{$product->name}}</h2>
    <span id="product-id" data-id="{{$product->id}}"></span>
    <div class="container">
        <div class="row">
            <div class="col">
                <img src="{{Storage::url($product->image)}}" alt=""  height="250" class="w-75"><br>
                <button type="button" class=" mt-4 btn btn-outline-info" id="nearest">find market near me</button>
                <div class="m-2 custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input " name="setRadius" id="setRadius" >
                    <label class="custom-control-label" for="setRadius">set distance in kilometers</label>
                </div>
                <script id="markets" type="text/x-jquery-tmpl">
            <li><a href="{{route('markets.show', [$market ?? ''])}}}">${name}</a>: ${distance}</li>
             <span>location: ${location}</span></li>
        </script>
                <input type="text" name="radius" id="radius">
                <ul id="MarketList" class="list-unstyled" >

                </ul>
            </div>

<div class="col">
    <h4>price: {{$product->price}}$</h4>
    <span>count: {{$product->count}}</span><br>
    @if(isset($product->categories))
        <span class="font-weight-bold">categories:</span>
        @foreach($product->categories as $category)
            <a href="{{route('category-show', [$category->id])}}" class="badge badge-info">{{$category->name}}</a>
        @endforeach
    @endif
    <div class="p-4 my-4 border rounded ">
        <span>description:</span><br>
        <p>{{$product->description}}</p>
    </div>

         @if($product->isAvaible())
         <div id="addBasket">
        <add-product :product="{{$product}}"
        /></div>
    @else
          <h3 class="font-weight-bold text-dark">нет в наличии</h3>
        @endif
        @csrf

    <br> <span>available in magazines:</span><br>
    @if(isset($product->markets))
    @foreach($product->markets  as $market)
        <h5><a href="{{route('marketShow', [$market->id])}}">{{$market->name}}</a></h5>
    @endforeach


     @endif
    <div id="basket_details"></div>
</div>

    </div> @if(isset($recommendProducts))
        <h3 class="my-2 text-center">recommend products</h3>
        <div class="row">

    @foreach( $recommendProducts as $product)
            <div class="col-3 m-4 border rounded">
                <img src="{{Storage::url($product->image)}}" alt="" width="" height="100" class="w-100">
                <h4><a href="{{route('productShow', [$product])}}">{{substr($product->name, 0 , 30)}}</a></h4>
                @foreach($product->categories as $category)
                    <span class="badge badge-info">
                           <a href="{{route('category-show', [$category])}}" class="text-white"> {{$category->name}}</a>
                            </span>
                @endforeach
                <br><span class="text-success font-weight-bold">price: {{$product->price}}</span>
            </div>
        @endforeach
        </div> @endif
        <hr>
        <comments-component :product_id="{{$product->id}}" :user_id="{{auth()->id() ?? 0}}" />
    </div>

@endsection