routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('markets', 'MarketController');

Route::get('getProducts', 'HomeController@getProducts');
Route::get('/productShow/{product}', 'HomeController@ProductShow')->name('productShow');
Route::get('/marketShow/{market}', 'HomeController@MarketShow')->name('marketShow');
Route::get('markets/{market}/products', 'MarketController@MarketProducts')->name('markets.products');
Route::post('markets/addProduct', 'MarketController@addProduct');
Route::post('markets/removeProduct', 'MarketController@removeProduct');
Route::get('market-all', 'HomeController@markets')->name('markets');
Route::get('category-all', 'HomeController@categories')->name('categories');
Route::get('category-all/{category}/show', 'HomeController@categoryShow')->name('category-show');

Route::get('/search', 'SearchController@search')->name('search');
Route::post('/getNearestMarkets/', 'SearchController@nearest')->name('nearest');

Route::group(['middleware' => 'basket_is_not_empty'], function (){
    Route::get('basket', 'BasketController@basket')->name('basket');
    Route::get('basket/place', 'BasketController@basketPlace')->name('basketPlace');
    Route::post('basket/remove/{product}', 'BasketController@basketRemove')->name('basketRemove');
    Route::post('basket/place', 'BasketController@basketConfirm')->name('basketConfirm');
});
Route::post('/basket/add/{product}', 'BasketController@basketAdd')->name('basketAdd');
Route::get('/orders', 'OrderController@index')->name('orders.index');
Route::get('/order/{order}', 'OrderController@show')->name('orders.show');
Route::get('/incomingOrders', 'OrderController@incomingOrders')->name('incomingOrders');
Route::get('incomingOrderShow/{order}', 'OrderController@incomingOrderShow')->name('incomingOrderShow');

Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');


Route::get('/getBasket', 'BasketController@getBasketForAjax');
//Route::get('/getCountOfProducts', 'BasketController@getCountOfProducts');

Route::get('/getCategories', 'CategoriesController@getCategories');
Route::get('/getProducts', 'HomeController@getProducts');
Route::post('/uploadImageForProduct', 'ProductsController@image');
Route::get('/getIncomingOrders', 'OrderController@getIncomingOrders');
Route::get('/', function (){
    return view('vue');
})->name('vue-home');


Route::get('/statistic', 'StatisticController@index')->name('statistic');
Route::get('/getStatistic', 'StatisticController@getStatistic');
Route::get('/getTopTrendingProducts', 'StatisticController@getTopTrendingProducts');
Route::get('/getOrdersStatistic', 'StatisticController@getOrdersStatistic');
Route::get('/getTotalOrdersSum', 'StatisticController@getTotalOrdersSum');
Route::get('/getCategoriesStatistic', 'StatisticController@getCategoriesStatistic');


Route::get('login/google', 'Auth\LoginController@redirectToProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" style="height: 100%!important;" >
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }} ">
    <meta name="Authorization" content="Beaver {{cookie('jwt_token')}}">
    <title>@yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ mix('js/app.js') }}"></script>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

     <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body class="d-flex flex-column h-100" style="height: 100%!important;">
    <div id="app" class="d-flex flex-column">
        <header >
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav  mr-auto">

                    </ul>
                        <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto text-capitalize">
                        <!-- Authentication Links -->

                        <li class="nav-item">
                            <a class="nav-link" href="{{route('categories')}}">categories</a>
                        </li>
                        <li class="nav-item  " id="basket">
                            <basket-component ></basket-component>
                        </li>
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else   <li class="nav-item">
                            <a class="nav-link" href="{{route('orders.index')}}">my orders </a>
                        </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                dashboard <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('products.index') }}">
                                    products edit
                                </a> <a class="dropdown-item" href="{{ route('markets.index') }}">
                                    markets edit
                                </a>
                                <a class="dropdown-item" href="{{ route('incomingOrders') }}">
                                    incoming orders
                                </a>
                                @admin
                                <a class="dropdown-item" href="{{ route('categories.index') }}">
                                    categories edit
                                </a>
                                <a class="dropdown-item" href="{{route('statistic')}}">statistic</a>
                                @endadmin
                            </div>

                        </li>
                    </ul>
                </div>
        </nav>
        </header>
        <main class="py-4">
            @if(session()->has('success'))
                <p class="alert alert-success"> {{session()->get('success')}}</p>
            @endif
            @if(session()->has('warning'))
                <p class="alert alert-warning">{{session()->get('warning')}}</p>
            @endif
            @yield('content')
        </main>
    </div>
<footer class=" mt-auto bg-dark">
    <div id="footer" class="container-fluid">
        <footer-component ></footer-component>
    </div>
    <script src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js" ></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYChPmR6U21PRhlVzhUG5Ue1OvW3raOJw&libraries=places&callback=initialize" async defer></script>
     <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
    <script src="/js/stripe.js"></script>
    <script src="/js/mapInput.js"></script>
    <script src="/js/MarketProducts.js"></script>
    <script src="/js/NearestMarkets.js"></script>

   </footer>
</body>
</html>